# -*- coding: utf-8 -*-
"""task-36.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EuxChezFh9H772RPJQvoeoO-aheCFAs_
"""



"""**Note: Try to avoid *GROUP BY* clause to solve the problems**

For the problems use the *Health Insurance Claim* dataset. You can get the details as well as the dataset from [here](https://www.kaggle.com/datasets/thedevastator/insurance-claim-analysis-demographic-and-health).

### **Problem 1:** What are the top 5 patients who claimed the highest insurance amounts?

### **Problem 2:** What is the average insurance claimed by patients based on the number of children they have?

### **Problem 3:** What is the highest and lowest claimed amount by patients in each region?

### **Problem 4:** What is the percentage of smokers in each age group?

### **Problem 5:** What is the difference between the claimed amount of each patient and the first claimed amount of that patient?

### **Problem 6:** For each patient, calculate the difference between their claimed amount and the average claimed amount of patients with the same number of children.

### **Problem 7:** Show the patient with the highest BMI in each region and their respective rank.

### **Problem 8:** Calculate the difference between the claimed amount of each patient and the claimed amount of the patient who has the highest BMI in their region.

### **Problem 9:** For each patient, calculate the difference in claim amount between the patient and the patient with the highest claim amount among patients with the same bmi and smoker status, within the same region. Return the result in descending order difference.

### **Problem 10:** For each patient, find the maximum BMI value among their next three records (ordered by age).

### **Problem 11:** For each patient, find the rolling average of the last 2 claims.

### **Problem 12:** Find the first claimed insurance value for male and female patients, within each region order the data by patient age in ascending order, and only include patients who are non-diabetic and have a bmi value between 25 and 30.
"""

-- 1
select * from insurance_data
order by claim desc limit  5;

select *,dense_rank() over(order by claim desc) from insurance_data limit 5;

-- 2
select children,avg_claim from (select *,
avg(claim) over(partition by children) as avg_claim,
row_number() over(partition by children) as row_num
from insurance_data) t
where t.row_num=1;

-- 3
select region,min_claim,max_claim from (select *,
min(claim) over(partition by region) as min_claim,
max(claim) over(partition by region) as max_claim,
row_number() over(partition by region) as row_num
from insurance_data) t
where t.row_num=1;

--  5
select *,
claim - first_value(claim) over() as diff
from insurance_data;

-- 6
select *,
claim - avg(claim) over(partition by children)
from insurance_data;


-- 7
select * from (select *,
rank() over(partition by region order by bmi desc) as group_rank,
rank() over(order by bmi desc) as overall_rank
from insurance_data) t
where t.group_rank=1;

-- 8
select *,
claim - first_value(claim) over(partition by region order by bmi desc)
from insurance_data;

-- 9
select *,
(max(claim) over(partition by region,smoker) - claim) as claim_diff
from insurance_data
order by claim_diff desc;

-- 10
select *,
max(bmi) over(order by age rows between 1 following and 3 following)
from insurance_data;


-- 11
select *,
avg(claim) over(rows between 2 preceding and 1 preceding)
from insurance_data;

-- 12
with filtered_data as (
 select * from insurance_data
 where diabetic='No' and bmi between 25 and 30)

select region,gender,first_claim from (select *,
first_value(claim) over(partition by region,gender order by age) as first_claim,
row_number() over(partition by region,gender order by age) as row_num
from filtered_data) t
where t.row_num=1

